### ISSUE TITLE
No application/ld+json schema

### ISSUE THREAD

**Issue by bhatvikrant** [alexkates/hashnode-next#3]
Would be nice if this template supports Schema like it is there in official [starter-kit](https://github.com/Hashnode/starter-kit/blob/efce90bd207e1be4acdbd0101a8556c2c92a24d3/packages/blog-starter-kit/themes/personal/pages/%5Bslug%5D.tsx#L123)

**Comment by alexkates** [comment]
Thanks, @bhatvikrant. This seams reasonable to me. I'll take a look over the next couple of days and report back.

**Comment by alexkates** [comment]
@bhatvikrant both /blog and /blog[slug] now have ld+json embedded in the page and is generated based on the Hashnode publication and post.

Thanks again for reporting this.
![image](https://github.com/alexkates/hashnode-next/assets/632749/dd945ebd-fa10-4381-8701-6532b7e49f20)

**Comment by bhatvikrant** [comment]
Thanks @alexkates!
